
services:

  php-fpm:
    build:
      args:
        user: laraveluser
        uid: 1000
      context: .
      dockerfile: docker/php-fpm/Dockerfile
    container_name: php-fpm
    working_dir: /var/www
    volumes:
      - ./task-manager:/var/www
    networks:
      - app-network

  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./task-manager:/var/www
      - ./docker/nginx/configuration/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php-fpm
    networks:
      - app-network

  db:
    image: mysql:latest
    restart: always
    container_name: mysql-db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_DATABASE: "laravel"
      MYSQL_USER: "laraveluser"
      MYSQL_PASSWORD: "password"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network: